<a href="https://colab.research.google.com/github/Markov887/Programming-languages/blob/main/%D0%9F%D0%A08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 Задана матрица порядка n и число к. Разделить элементы k-й строки
на диагональный элемент, расположенный в этой строке.

2 Задана квадратная матрица. Получить транспонированную матрицу
(перевернутую относительно главной диагонали) и вывести на экран.

In [6]:
from numpy import *
n = int(input("Введите размер матрицы: "))
k = int(input("Введите номер строки k (от 0 до n-1): "))
a = np.random.randint(1, 50, size=(n, n))
print(a)
for i in range(len(a)):
  deli = a[k][i] / a[i][i]
  print(a[k][i], '/', a[i][i], '=', deli)

Введите размер матрицы: 5
Введите номер строки k (от 0 до n-1): 3
[[43 36 45 25 35]
 [10 42 15  4 30]
 [37 40 28  6 27]
 [11 40 19 15 16]
 [10 22 47  5 30]]
11 / 43 = 0.2558139534883721
40 / 42 = 0.9523809523809523
19 / 28 = 0.6785714285714286
15 / 15 = 1.0
16 / 30 = 0.5333333333333333


In [8]:
from numpy import *
n = int(input("Введите размер матрицы: "))
b = np.random.randint(1,50, size=(n,n))
print(b)
a = b.transpose()
print(a)

Введите размер матрицы: 5
[[49 48 46 10 10]
 [ 5  7 24 27  4]
 [46 34 46  8 12]
 [15  9  4 10 20]
 [33  2  5 23 38]]
[[49  5 46 15 33]
 [48  7 34  9  2]
 [46 24 46  4  5]
 [10 27  8 10 23]
 [10  4 12 20 38]]
